### ISSUE TITLE
一直显示loading

### ISSUE THREAD

**Issue by SnowdropK** [hua1995116/git-down-repo#1]
大佬，我安装了这个node工具后，下载
https://github.com/aspnet/Docs/tree/master/aspnetcore/tutorials/signalr/sample 
这个url，但一直提示在loading，很神奇，不知道是什么原因

好吧，等了一会，发现是下载速度有点慢，多等一会就下好了@-@

**Comment by hua1995116** [comment]
是因为你这个仓库文件太多了。需要解析的东西有点多。

**Comment by hua1995116** [comment]
后面我会考虑给loading加点东西，现在的loading时间太长可能会误认为出了错。先关issues了哈。
