### ISSUE TITLE
下载某一文件夹提示失败，结果本地全部显示

### ISSUE THREAD

**Issue by bosens-China** [hua1995116/git-down-repo#4]
其次，建议把cli部分和核心部分分离开，这样可以让别人下载核心部件来完成定制的功能
不成熟猜想
``` js
const {down} = require('xxx')
down(`xxx`).then(e => {
})
```

**Comment by hua1995116** [comment]
意思是提示失败，但是还是加载成功了是吗，能提供一下示例么。

**Comment by bosens-China** [comment]
按照描述我可以下载某一仓库下的指定文件夹
`https://github.com/zhongsp/TypeScript/doc`
这里是我下载的文件夹地址，结果发生了错误，我推测可能跟网络波动也有关系

**Comment by hua1995116** [comment]
我测试了一下，本地网络比较慢，但是翻墙的网确实很快就下好了。还有，现在也是支持 require 的形式的呢。你是期望有更多的一些回调参数是吧？

**Comment by bosens-China** [comment]
> 我测试了一下，本地网络比较慢，但是翻墙的网确实很快就下好了。还有，现在也是支持 require 的形式的呢。你是期望有更多的一些回调参数是吧？

是的，期待一下与cli本身分离开来，这样我可以实现一些定制的需求，比如支持自定义保存目录地址，以及返回的是promise类型

**Comment by hua1995116** [comment]
这个没问题，我修改一下。网络问题只能靠你自己了。(手动笑抽)
